name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.14.1
          run_install: |
            - recursive: true
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Build packages
        run: pnpm recursive run build
        env:
          CI: true

      - name: Run tests
        run: pnpm recursive run test
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Lint files
        run: pnpm recursive run lint
        env:
          CI: true

      - name: Check types
        run: pnpm recursive run typecheck
        env:
          CI: true
