name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.7.6
          run_install: |
            - recursive: true
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Install playwright browsers
        run: pnpx playwright install-deps chromium
        env:
          CI: true

      - name: Build packages
        run: pnpm run build:packages
        env:
          CI: true

      - name: Lint files
        run: pnpm run lint
        env:
          CI: true

      - name: Check types
        run: pnpm run typecheck
        env:
          CI: true

      - name: Run tests
        run: pnpm run test
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Build examples
        run: pnpm run build:examples
        env:
          CI: true
